name: cervezapp
description: Aplicaci贸n Flutter para gesti贸n local de productos, clientes y ventas (v1.7)
publish_to: "none"

version: 1.7.0+17

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  STATE MANAGEMENT
  provider: ^6.1.2

  #  TOASTS & SNACKS
  fluttertoast: ^8.2.4

  #  UI & ICONS
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.6.0

  #  DATE FORMATTING
  intl: ^0.19.0

  #  ANIMACIONES Y UTILIDADES
  animations: ^2.0.11
  flutter_animate: ^4.3.0

  #  CMARA Y ARCHIVOS
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  file_picker: ^8.0.0+1
  share_plus: ^7.2.2

  # 锔 PERSISTENCIA LOCAL (para futuras versiones)
  shared_preferences: ^2.3.3
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# Configuraci贸n para generar iconos de la aplicaci贸n
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/icon/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/logo.png"
  image_path: "assets/icon/logo.png"

